# Generated by Django 3.1.3 on 2021-02-01 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category'], 'verbose_name': 'producto', 'verbose_name_plural': 'proyectos'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
